gaussian_noise:
  mean: 0
  std: 20

speckle_noise:
  intensity: 0.1

salt_and_pepper_noise:
  salt_prob: 0.05
  pepper_prob: 0.05

poisson_noise: {}

gaussian_blur:
  sigma: 5

motion_blur:
  size: 15
  angle: 45

beam_hardening_artifact:
  intensity: 0.2