speckle_noise:
  intensity: [0.1, 0.3]

salt_and_pepper_noise:
  salt_prob: [0.05, 0.15]
  pepper_prob: [0.05, 0.15]

poisson_noise:
  intensity: [0.1, 1.5]

# gaussian_noise:
#   mean: 0
#   std: 20

# gaussian_blur:
#   sigma: 5

# motion_blur:
#   size: 15
#   angle: 45

# beam_hardening_artifact:
#   intensity: 0.2
