gaussian_noise:
  mean: 0
  std:
    min: 20
    max: 100

speckle_noise:
  intensity:
    min: 0.1
    max: 0.5

salt_and_pepper_noise:
  salt_prob:
    min: 0.05
    max: 0.20
  pepper_prob:
    min: 0.05
    max: 0.20

poisson_noise: {}

gaussian_blur:
  sigma: 5

motion_blur:
  size: 15
  angle: 45

beam_hardening_artifact:
  intensity: 0.2