model:
  n_channels: 1
  learning_rate: 0.0001

dataloader:
  image_dir: "data/LungSegmentation/CXR_png/"
  batch_size: 32
  num_workers: 12
  train_ratio: 0.8
  noise_types: ["salt_and_pepper_noise"]

training:
  accelerator: "cuda"
  max_epochs: 50
  log_every_n_steps: 10