model:
  n_channels: 1
  learning_rate: 0.0001

dataloader:
  image_dir: "data/main_dataset/original_images/"
  noised_image_dir: "data/main_dataset/final_images/"
  batch_size: 10
  num_workers: 12
  train_ratio: 0.8

training:
  accelerator: "cuda"
  max_epochs: 50
  log_every_n_steps: 10