# histogram_equalization: {}

# clahe:
#   clip_limit: 0.01
#   nbins: 256

# gamma_correction:
#   gamma: 3

# unsharp_masking:
#   radius: 1.0
#   amount: 2.0

# gaussian_filter:
#   sigma: 1

# wiener_filter:
#   balance: 0.1

median_filter:
  kernel_size: 3

bilateral_filter:
  sigma_color: 0.4
  sigma_spatial: 0.6
  bins: 64

non_local_means:
  h: 0.018

local_adaptive_median_filter:
  radius: 5
  multiplier: 1.0

frost_filter:
  window_size: 7
  initial_K: 0.6

wavelet_denoise_filter:
  wavelet: 'db1'
  mode: 'soft'