model:
  n_channels: 1
  n_classes: 1
  learning_rate: 0.001

dataloader:
  image_dir: "data/LungSegmentation/CXR_png_200/"
  masks_dir: "data/LungSegmentation/masks_200/"
  batch_size: 4
  num_workers: 4
  train_ratio: 0.8

training:
  accelerator: "cuda"
  max_epochs: 50
  log_every_n_steps: 10