model:
  n_channels: 1
  n_classes: 1
  learning_rate: 0.001

dataloader:
  image_dir: "data/main_dataset/final_images/"
  masks_dir: "data/main_dataset/masks/"
  batch_size: 16
  num_workers: 8
  train_ratio: 0.8

training:
  accelerator: "cuda"
  max_epochs: 15
  log_every_n_steps: 10